version: '3'

# Networks
networks:
  fiesta:

# Volumes
volumes:
  db_data:

services:
  # Backend Webserver
  nginx:
    image: nginx:stable-alpine
    container_name: fiesta-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - redis-server
    networks:
      - fiesta

  # PHP
  php:
      build:
        context: ./backend
        dockerfile: Dockerfile
      entrypoint: ["/bin/sh", "./backend/entrypoint.sh"]
      container_name: fiesta-php
      volumes:
          - ./backend:/var/www
      ports:
          - 9000:9000
      depends_on:
        - nginx
      networks:
          - fiesta

  # Database Services
  db:
    image: jbergstroem/mariadb-alpine
    container_name: fiesta-db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
    networks:
          - fiesta

  # Adminer
  adminer:
    container_name: fiesta-adminer
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: homestead
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8080:8080
    networks:
      - fiesta

  # Redis
  redis-server:
    image: redis:5-alpine
    container_name: fiesta-redis
    ports:
      - 6379:6379
    networks:
      - fiesta

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fiesta-frontend
    volumes:
        - ./frontend:/var/www
    ports:
        - 80:80
    depends_on:
      - php
      - db
      - redis-server
      - nginx
    networks:
        - fiesta
