version: '3'

# Networks
networks:
  fiesta:

# Volumes
volumes:
  db_data:

services:
  # Websever
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - fiesta

  # PHP
  php:
      build:
          context: ./backend
          dockerfile: Dockerfile
      container_name: php
      volumes:
          - ./backend:/var/www
      ports:
          - "9000:9000"
      networks:
          - fiesta

  # Database Services
  db:
    image: jbergstroem/mariadb-alpine
    container_name: fiesta-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev

  # Adminer
  adminer:
    container_name: fiesta-db
    image: adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: fiesta
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 9000:8080
    networks:
      - fiesta


